### ISSUE TITLE
google_dl doesn't do anything.

### ISSUE THREAD

**Issue by kenorb** [mycognitive/google_dl#1]
The script doesn't downloads files anymore (it was some time ago).

Example:

    $ google_dl -v http://example.com
    $ google_dl "foo" -f pdf

I'm expecting that script will download the files as before.
It may be the issue in xgoogle lib, if so, send PR into [mycognitive/xgoogle](https://github.com/mycognitive/xgoogle).

**Comment by Vort** [comment]
@kenorb, please try this fix:
https://github.com/Vort/xgoogle/commit/11d3a1bbaaf9491c8559c6e3764d5ecf453a7a85

**Comment by kenorb** [comment]
@Vort Ok, thanks, let me check within few hours.

**Comment by kenorb** [comment]
@Vort Works, thank you.
