### ISSUE TITLE
Support for omitted results

### ISSUE THREAD

**Issue by kenorb** [mycognitive/google_dl#2]
The following command downloads only one file:

    google_dl -s mast.queensu.ca -f pdf ""

The expected result is to download all the files.

For example when googling `site:mast.queensu.ca filetype:pdf` it also shows one file, but when I click on `repeat the search with the omitted results included`, it shows 6k of other files.

The above script should automatically follow the omitted result criteria, so it can download all the files.

If the option can be parameterized, this method can be activated by specifying `-r` (to _repeat the search with the omitted results included_).

Est. 2-4h

**Comment by lu43n** [comment]
Done in mycognitive/google_dl #3 and mycognitive/xgoogle #12 PR

Time: 2h
