### ISSUE TITLE
Doesn't return all the repeated results

### ISSUE THREAD

**Issue by kenorb** [mycognitive/google_dl#8]
```
$ google_dl -v -x -r "site:www.imdb.com/board"
site:www.imdb.com/board
Trying to download results from page #1  (results 1-47)
...

$ python3
>>> from xgoogle.search import GoogleSearch
>>> gs = GoogleSearch("site:www.imdb.com/board", repeat=True)
```

The tool is only downloading 47 items, but Google reports [5,740 results](https://www.google.co.uk/search?q=site%3Awww.imdb.com%2Fboard&oq=site%3Awww.imdb.com%2Fboard&ie=UTF-8#q=site:www.imdb.com/board&filter=0). It needs to take into account all of them.

The fix should be either in this repo or in [xgoogle](https://github.com/mycognitive/xgoogle), depending where is the problem.

![image](https://cloud.githubusercontent.com/assets/266306/22783586/6366cb38-eec4-11e6-8998-dad2a9861505.png)

**Comment by RabsRincon** [comment]
Ey!

Do you mean that it should download all 5 thousand? Not quite clear from what you say

**Comment by flhp** [comment]
Hi, my commit should fix the problem.
Now it should download the correct amount of items (~100).
The number 5740 isn't really correct, it's only what google estimates. If you actually go to the last page of the search results, you'll see the number is around 100.

Cheers!

**Comment by kenorb** [comment]
Yes, it should download all available results when `-r` is specified. Sounds like PR fixes the problem.
